services:
  web:
    ports:
      - "8000:8000"
    container_name: fastapi2
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
