version: "3"

services:
  nodejs:
    container_name: nodejs
    image: node:20-alpine
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - nodemongonetwork
    command: ["node", "server.js"]

  mongo:
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongovolume:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - nodemongonetwork

  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - ME_CONFIG_BASICAUTH=${ME_CONFIG_BASICAUTH}
    networks:
      - nodemongonetwork

volumes:
  mongovolume:

networks:
  nodemongonetwork:
