
services:
  django-web-1:
    build: .
    container_name: django-web-2
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - django_data:/app/db.sqlite3
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  django_data:

