services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: raimu
      POSTGRES_PASSWORD: raimu
      POSTGRES_DB: raimu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: raimu@example.com
      PGADMIN_DEFAULT_PASSWORD: raimu
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
